services:
  valkey:
    image: valkey/valkey:alpine
  valkey-exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: "valkey:6379"
    labels:
      prometheus.auto.enable: "true"
      prometheus.auto.port: "9121"
      prometheus.auto.label.instance: "lol"
      prometheus.auto.label.service: "valkey"
      prometheus.auto.label.component: "cache"
      prometheus.auto.label.environment: "development"
  collector:
    image: ghcr.io/shyim/prometheus-docker-collector:latest
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml

configs:
  prometheus:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'collector'
          http_sd_configs:
            - url: 'http://collector:8080/sd'